[package]
name = "amqp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
test-client = ["dep:url"]

[dependencies]
serde.workspace = true
serde_amqp.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url = { workspace = true, optional = true }
