<Project>
  <PropertyGroup>
    <SwitchyardSdkSelector>declared-current</SwitchyardSdkSelector>
    <SwitchyardServiceBusVersion>[7.21.0]</SwitchyardServiceBusVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>
</Project>
