[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "switchyard"
path = "src/main.rs"

[dependencies]
auth.workspace = true
clap.workspace = true
cluster.workspace = true
domain.workspace = true
flume.workspace = true
protocol-amqp.workspace = true
rustls.workspace = true
storage.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
amqp = { workspace = true, features = ["test-client"] }
base64.workspace = true
hmac.workspace = true
rcgen.workspace = true
rustls.workspace = true
sha2.workspace = true
tempfile.workspace = true
testkit.workspace = true
tokio-rustls.workspace = true
url.workspace = true
