[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "switchyard"
path = "src/main.rs"

[dependencies]
clap.workspace = true
cluster.workspace = true
domain.workspace = true
flume.workspace = true
storage.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
testkit.workspace = true
tokio.workspace = true

